/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BINTANG
 */
public class FrmMaster extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    private String SQL;
    private String delete;
    /**
     * Creates new form FrmMaster
     */
    public FrmMaster() {
        initComponents();
        tampilDataCbg();
        tampilDataDtm();
        tampilData();
    }
    
    private void tampilDataCbg() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        model.addColumn("Kode Cabang");
        model.addColumn("Nama Cabang");
        model.addColumn("No. Telp");
        model.addColumn("Alamat");
        model.addColumn("Kota");
        model.addColumn("Provinsi");
        tableCbg.setModel(model);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM cabang";
            java.sql.ResultSet rest = stmt.executeQuery(SQL);
            while (rest.next()) {
                model.addRow(new Object[] {
                    rest.getString("kodeCbg"),
                    rest.getString("nama"),
                    rest.getString("noTelp"),
                    rest.getString("alamat"),
                    rest.getString("kota"),
                    rest.getString("provinsi")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void tampilDataDtm() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        model.addColumn("Kode Departemen");
        model.addColumn("Nama Departemen");
        model.addColumn("Bagian");
        tableDtm.setModel(model);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM departemen";
            java.sql.ResultSet rest = stmt.executeQuery(SQL);
            while (rest.next()) {
                model.addRow(new Object[] {
                    rest.getString("kodeDtm"),
                    rest.getString("nama"),
                    rest.getString("bagian")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void tampilData() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        model.addColumn("Kode Jabatan");
        model.addColumn("Nama Jabatan");
        model.addColumn("Gaji");
        tableJabatan.setModel(model);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM jabatan";
            java.sql.ResultSet rest = stmt.executeQuery(SQL);
            while (rest.next()) {
                model.addRow(new Object[] {
                    rest.getString("kodeJbtn"),
                    rest.getString("nama"),
                    rest.getString("gaji")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void bersih() {
        txtKodeJbtn.setText("");
        txtNamaJbtn.setText("");
        txtGaji.setText("");
        txtKodeCbg.setText("");
        txtNamaCbg.setText("");
        txtTelpCbg.setText("");
        txtAlamatCbg.setText("");
        txtKotaCbg.setText("");
        txtProvCbg.setText("");
        txtKodeDtm.setText("");
        txtNamaDtm.setText("");
        txtBagian.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKodeCbg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaCbg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelpCbg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKotaCbg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProvCbg = new javax.swing.JTextField();
        btnBatal1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        btnTambah1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatCbg = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCbg = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtKodeDtm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNamaDtm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBagian = new javax.swing.JTextField();
        btnTambah2 = new javax.swing.JButton();
        btnUpdate2 = new javax.swing.JButton();
        btnHapus2 = new javax.swing.JButton();
        btnBatal2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDtm = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtKodeJbtn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNamaJbtn = new javax.swing.JTextField();
        txtGaji = new javax.swing.JTextField();
        btnHapus3 = new javax.swing.JButton();
        btnBatal3 = new javax.swing.JButton();
        btnTambah3 = new javax.swing.JButton();
        btnUpdate3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableJabatan = new javax.swing.JTable();

        setTitle("Menu Manajer");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Data Cabang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Kode Cabang   :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama Cabang  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("No. Telp  :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Alamat   :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Kota        :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Provinsi  :");

        btnBatal1.setText("Batal");
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });

        btnUpdate1.setText("Update");
        btnUpdate1.setEnabled(false);
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnHapus1.setText("Hapus");
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        btnTambah1.setText("Tambah");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        txtAlamatCbg.setColumns(20);
        txtAlamatCbg.setRows(5);
        jScrollPane1.setViewportView(txtAlamatCbg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtKodeCbg))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaCbg))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelpCbg))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtKotaCbg))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtProvCbg))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambah1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate1)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnBatal1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKodeCbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaCbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelpCbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKotaCbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProvCbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah1)
                    .addComponent(btnUpdate1)
                    .addComponent(btnHapus1)
                    .addComponent(btnBatal1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableCbg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tableCbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCbgMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCbg);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Data Departemen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Kode Departemen   :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Nama Departemen  :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Bagian  :");

        btnTambah2.setText("Tambah");
        btnTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah2ActionPerformed(evt);
            }
        });

        btnUpdate2.setText("Update");
        btnUpdate2.setEnabled(false);
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });

        btnHapus2.setText("Hapus");
        btnHapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus2ActionPerformed(evt);
            }
        });

        btnBatal2.setText("Batal");
        btnBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtKodeDtm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaDtm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtBagian))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTambah2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate2)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnBatal2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKodeDtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNamaDtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah2)
                    .addComponent(btnUpdate2)
                    .addComponent(btnHapus2)
                    .addComponent(btnBatal2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableDtm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDtm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDtmMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDtm);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Jabatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Kode Jabatan    :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Nama Jabatan   :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Gaji   :");

        btnHapus3.setText("Hapus");
        btnHapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus3ActionPerformed(evt);
            }
        });

        btnBatal3.setText("Batal");
        btnBatal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal3ActionPerformed(evt);
            }
        });

        btnTambah3.setText("Tambah");
        btnTambah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah3ActionPerformed(evt);
            }
        });

        btnUpdate3.setText("Update");
        btnUpdate3.setEnabled(false);
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKodeJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaJbtn)
                            .addComponent(txtGaji, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTambah3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate3)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnBatal3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKodeJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNamaJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah3)
                    .addComponent(btnUpdate3)
                    .addComponent(btnHapus3)
                    .addComponent(btnBatal3))
                .addContainerGap())
        );

        tableJabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJabatanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableJabatan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah2ActionPerformed
        // TODO add your handling code here:
        String kodeDtm = txtKodeDtm.getText();
        String namaDtm = txtNamaDtm.getText();
        String bagian  = txtBagian.getText();
        try {
            SQL = "INSERT INTO departemen(kodeDtm,nama,bagian) "
                    + "VALUES('"+kodeDtm+"', "
                    + "('"+namaDtm+"'), "
                    + "'"+bagian+"' )";
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilDataDtm();
        bersih();
    }//GEN-LAST:event_btnTambah2ActionPerformed

    private void btnHapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus2ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini ?", "Warning!", JOptionPane.YES_NO_OPTION);
        
        if (option == 0) {
            
            try {
                delete = "DELETE FROM departemen WHERE kodeDtm='"+txtKodeDtm.getText()+"'";
                Connection conn = koneksi.getConnection();
                java.sql.PreparedStatement pst = conn.prepareStatement(delete);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus! !");
            
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampilDataDtm();
            bersih();
        } else {
            
        }
    }//GEN-LAST:event_btnHapus2ActionPerformed

    private void btnBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal2ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_btnBatal2ActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini ?", "Warning!", JOptionPane.YES_NO_OPTION);
        
        if (option == 0) {
            
            try {
                delete = "DELETE FROM cabang WHERE kodeCbg='"+txtKodeCbg.getText()+"'";
                Connection conn = koneksi.getConnection();
                java.sql.PreparedStatement pst = conn.prepareStatement(delete);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus! !");
            
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampilDataCbg();
            bersih();
        } else {
            
        }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        // TODO add your handling code here:
        try {
            SQL = "INSERT INTO cabang VALUES"
                    + "('"+txtKodeCbg.getText()+"', "
                    + "'"+txtNamaCbg.getText()+"', "
                    + "'"+txtTelpCbg.getText()+"', "
                    + "'"+txtAlamatCbg.getText()+"', "
                    + "'"+txtKotaCbg.getText()+"', "
                    + "'"+txtProvCbg.getText()+"')";
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilDataCbg();
        bersih();
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        try {
            SQL = "UPDATE cabang SET nama='"+txtNamaCbg.getText()+"', "
                    + " noTelp='"+txtTelpCbg.getText()+"', "
                    + " alamat='"+txtAlamatCbg.getText()+"', "
                    + " kota='"+txtKotaCbg.getText()+"', "
                    + " provinsi='"+txtProvCbg.getText()+"' "
                    + "WHERE kodeCbg='"+txtKodeCbg.getText()+"'";
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilDataCbg();
        bersih();
        btnTambah1.setEnabled(true);
        txtKodeCbg.setEnabled(true);
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void tableCbgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCbgMouseClicked
        // TODO add your handling code here:
        int baris = tableCbg.rowAtPoint(evt.getPoint());
        txtKodeCbg.setText(tableCbg.getValueAt(baris, 0).toString());
        txtNamaCbg.setText(tableCbg.getValueAt(baris, 1).toString());
        txtTelpCbg.setText(tableCbg.getValueAt(baris, 2).toString());
        String alamat = tableCbg.getValueAt(baris, 3).toString();
        txtAlamatCbg.setText(alamat);
        txtKotaCbg.setText(tableCbg.getValueAt(baris, 4).toString());
        txtProvCbg.setText(tableCbg.getValueAt(baris, 5).toString());
        btnTambah1.setEnabled(false);
        btnUpdate1.setEnabled(true);
        txtKodeCbg.setEnabled(false);
    }//GEN-LAST:event_tableCbgMouseClicked

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:
        try {
            SQL = "UPDATE departemen SET nama='"+txtNamaDtm.getText()+"', "
                    + " bagian='"+txtBagian.getText()+"' "
                    + "WHERE kodeDtm='"+txtKodeDtm.getText()+"'";
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilDataDtm();
        bersih();
        btnTambah2.setEnabled(true);
        txtKodeDtm.setEnabled(true);
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void btnTambah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah3ActionPerformed
        // TODO add your handling code here:
        String kode = txtKodeJbtn.getText();
        String nama = txtNamaJbtn.getText();
        String gaji  = txtGaji.getText();
        try {
            SQL = "INSERT INTO jabatan(kodeJbtn,nama,gaji) "
                    + "VALUES('"+kode+"', "
                    + "('"+nama+"'), "
                    + "'"+gaji+"' )";
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilData();
        bersih();
    }//GEN-LAST:event_btnTambah3ActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
        try {
            SQL = "UPDATE jabatan SET nama='"+txtNamaJbtn.getText()+"', "
                    + " gaji='"+txtGaji.getText()+"' "
                    + "WHERE kodeJbtn='"+txtKodeJbtn.getText()+"'";
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(SQL);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        btnTambah3.setEnabled(true);
        txtKodeJbtn.setEnabled(true);
        tampilData();
        bersih();
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void btnHapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus3ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini ?", "Warning!", JOptionPane.YES_NO_OPTION);
        
        if (option == 0) {
            
            try {
                delete = "DELETE FROM jabatan WHERE kodeJbtn='"+txtKodeJbtn.getText()+"'";
                Connection conn = koneksi.getConnection();
                java.sql.PreparedStatement pst = conn.prepareStatement(delete);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus! !");
            
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampilData();
            bersih();
        } else {
            
        }
    }//GEN-LAST:event_btnHapus3ActionPerformed

    private void btnBatal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal3ActionPerformed
        // TODO add your handling code here:
        txtKodeJbtn.setText("");
        txtNamaJbtn.setText("");
        txtGaji.setText("");
    }//GEN-LAST:event_btnBatal3ActionPerformed

    private void tableJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJabatanMouseClicked
        // TODO add your handling code here:
        int baris = tableJabatan.getSelectedRow();
        txtKodeJbtn.setText(model.getValueAt(baris, 0).toString());
        txtNamaJbtn.setText(model.getValueAt(baris, 1).toString());
        txtGaji.setText(model.getValueAt(baris, 2).toString());
        btnTambah3.setEnabled(false);
        btnUpdate3.setEnabled(true);
        txtKodeJbtn.setEnabled(false);
    }//GEN-LAST:event_tableJabatanMouseClicked

    private void tableDtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDtmMouseClicked
        // TODO add your handling code here:
        int baris = tableDtm.getSelectedRow();
        txtKodeDtm.setText(tableDtm.getValueAt(baris, 0).toString());
        txtNamaDtm.setText(tableDtm.getValueAt(baris, 1).toString());
        txtBagian.setText(tableDtm.getValueAt(baris, 2).toString());
        btnTambah2.setEnabled(false);
        btnUpdate2.setEnabled(true);
        txtKodeDtm.setEnabled(false);
    }//GEN-LAST:event_tableDtmMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnBatal2;
    private javax.swing.JButton btnBatal3;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnHapus2;
    private javax.swing.JButton btnHapus3;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JButton btnTambah2;
    private javax.swing.JButton btnTambah3;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton btnUpdate3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableCbg;
    private javax.swing.JTable tableDtm;
    private javax.swing.JTable tableJabatan;
    private javax.swing.JTextArea txtAlamatCbg;
    private javax.swing.JTextField txtBagian;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtKodeCbg;
    private javax.swing.JTextField txtKodeDtm;
    private javax.swing.JTextField txtKodeJbtn;
    private javax.swing.JTextField txtKotaCbg;
    private javax.swing.JTextField txtNamaCbg;
    private javax.swing.JTextField txtNamaDtm;
    private javax.swing.JTextField txtNamaJbtn;
    private javax.swing.JTextField txtProvCbg;
    private javax.swing.JTextField txtTelpCbg;
    // End of variables declaration//GEN-END:variables
}
